on:
  workflow_dispatch:
  
  
jobs: 
  run_build:
   runs-on: ubuntu-latest
   defaults: 
     run:
       working-directory: ./
   steps:
   
   - name: Check out the repository to the runner 
     uses: actions/checkout@v4
     
   - name: Prepare the environment
    
     run:
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y install python-is-python3 build-essential openssl pip python3-virtualenv python2.7 openssl
        sudo apt-get -y install git-all aptitude make gcc libtinfo5
        sudo aptitude -y install libssl-dev
        
   - name: make script file executable 
     run: chmod +x build_kernel.sh
     
   - name: Run script file
     run: ./build_kernel.sh
